language: python
sudo: true
python:
  - "2.7"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-matplotlib python-numpy python-qt4 python-qt4-gl python-qt4-sql python-scipy python-vtk python-xlrd python-xlwt xvfb
  - virtualenv --system-site-packages ~/venv && source ~/venv/bin/activate
  - pip install -r requirements.txt
script:
  - xvfb-run --server-args="-screen 0 1024x768x16" python dat/tests
